In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline
from collections import Counter 
from matplotlib import pyplot 
from numpy import where
from numpy import mean
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC
from sklearn import svm
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score 
from sklearn.metrics import precision_score 



In [103]:
df = pd.read_csv('./df1/df.csv') 

df.columns
ft = df
ft = ft.drop('label', axis=1) 
ft = ft.values
x_features = ft
df.drop(['BPD_mean','BPS_mean', 'HR_mean', 'SO_mean', 'TE_mean'],axis=1,inplace=True)
lb = df
lb = lb.values
y_labels = [] 
for x in lb:
    y_labels.append(x[0])

X = x_features 
y = y_labels
y = np.array(y)
counter = Counter(y) 
print(counter)


Counter({1: 734, 2: 512, 0: 92})


In [104]:
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=1)


model1 = KNeighborsClassifier( n_neighbors=5,weights='uniform', algorithm='auto', leaf_size=30,p=2, metric='minkowski', metric_params=None, n_jobs=None)
model2 = SVC( C=1.0,kernel='rbf', degree=3, gamma='auto', coef0=0.0,shrinking=True,probability=False, tol=0.001, cache_size=200, class_weight= {0:.2, 1:.3, 2:.5},verbose=False,max_iter=-1, decision_function_shape='ovr', random_state=None)
model3 = LinearSVC( penalty='l2',loss='squared_hinge', dual=False, tol=0.0001,C=1.0, multi_class='ovr', fit_intercept=True, intercept_scaling=1,class_weight= {0:.2, 1:.3, 2:.5},verbose=0, random_state=None, max_iter=1000)
model4 = RandomForestClassifier( bootstrap=True,class_weight= {0:.2, 1:.3, 2:.5}, criterion='gini',max_depth=2,max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, min_samples_leaf=1, min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=100,n_jobs=None, oob_score=False, random_state=0, verbose=0, warm_start=False)
model5 = LogisticRegression( penalty='l2',dual=False, tol=0.0001,C=1.0, fit_intercept=True, intercept_scaling=1,class_weight= {0:.2, 1:.3, 2:.5}, random_state=None, solver='lbfgs',max_iter=2000, multi_class='auto',verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)


In [105]:
for train_index, test_index in cv.split(X, y): 
    X_train, X_test = X[train_index], X[test_index] 
    y_train, y_test = y[train_index], y[test_index]

In [106]:
model1.fit(X_train,y_train) 
y_pred =model1.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y_test,y_pred))
print('KNeighborsClassifier Recall score', recall_score(y_test, y_pred, average='macro'))
print('KNeighborsClassifier Precision score', precision_score(y_test, y_pred, average='macro'))
          
model3.fit(X_train,y_train) 
y_pred =model3.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y_test,y_pred))
print('LinearSVC Recall score', recall_score(y_test, y_pred, average='macro'))
print('LinearSVC Precision score', precision_score(y_test, y_pred, average='macro'))
           
model4.fit(X_train,y_train) 
y_pred =model4.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y_test,y_pred))
print('RandomForestClassifier Recall score', recall_score(y_test, y_pred, average='macro'))
print('RandomForestClassifier Precision score', precision_score(y_test, y_pred, average='macro'))
            
model5.fit(X_train,y_train) 
y_pred =model5.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y_test,y_pred))
print('LogisticRegression Recall score', recall_score(y_test, y_pred, average='macro'))
print('LogisticRegression Precision score', precision_score(y_test, y_pred, average='macro'))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.56      0.58      0.57       147
           2       0.36      0.34      0.35       102

    accuracy                           0.52       267
   macro avg       0.64      0.64      0.64       267
weighted avg       0.51      0.52      0.51       267


 confusion_matrix:
 [[18  0  0]
 [ 0 85 62]
 [ 0 67 35]]
KNeighborsClassifier Recall score 0.6404561824729892
KNeighborsClassifier Precision score 0.6400117561946103
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        18
           1       0.66      0.68      0.67       147
           2       0.52      0.49      0.51       102

    accuracy                           0.63       267
   macro avg       0.71      0.72      0.72       267
weighted avg       0.63      0.63      0.63       267


 confusion_matrix:
 [[ 18   0   0]
 [  1 100  46]
 [  0  52  50]]
Line

In [107]:
test_later = pd.read_csv('./df1/test_later.csv')
test_later.columns
ft1 = test_later
ft1 = ft1.drop('label', axis=1) 
ft1 = ft1.values
x_features1 = ft1
test_later.drop(['BPD_mean','BPS_mean', 'HR_mean', 'SO_mean', 'TE_mean'],axis=1,inplace=True)
lb1 = test_later
lb1 = lb1.values
y_labels1 = [] 
for x in lb1:
    y_labels1.append(x[0])
X1 = x_features1 
y1 = y_labels1
y1 = np.array(y1)
counter1 = Counter(y1)
 

In [108]:
y_pred =model1.predict(X1) 
print(classification_report(y1,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y1,y_pred))
print('KNeighborsClassifier Recall score', recall_score(y1, y_pred, average='macro'))
print('KNeighborsClassifier Precision score', precision_score(y1, y_pred, average='macro'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.59      0.72      0.65        81
           2       0.42      0.30      0.35        57

    accuracy                           0.57       148
   macro avg       0.67      0.67      0.67       148
weighted avg       0.56      0.57      0.56       148


 confusion_matrix:
 [[10  0  0]
 [ 0 58 23]
 [ 0 40 17]]
KNeighborsClassifier Recall score 0.6714316655837124
KNeighborsClassifier Precision score 0.6722789115646258


In [109]:
y_pred =model3.predict(X1) 
print(classification_report(y1,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y1,y_pred)) 
print('LinearSVC Recall score', recall_score(y1, y_pred, average='macro'))
print('LinearSVC Precision score', precision_score(y1, y_pred, average='macro'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.58      0.62      0.60        81
           2       0.40      0.37      0.39        57

    accuracy                           0.55       148
   macro avg       0.66      0.66      0.66       148
weighted avg       0.54      0.55      0.54       148


 confusion_matrix:
 [[10  0  0]
 [ 0 50 31]
 [ 0 36 21]]
LinearSVC Recall score 0.661901667749621
LinearSVC Precision score 0.6617471675611211


In [110]:
y_pred =model5.predict(X1) 
print(classification_report(y1,y_pred))
print('\n confusion_matrix:\n', confusion_matrix(y1,y_pred)) 
print('LogisticRegression Recall score', recall_score(y1, y_pred, average='macro'))
print('LogisticRegression Precision score', precision_score(y1, y_pred, average='macro'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.62      0.26      0.37        81
           2       0.42      0.77      0.55        57

    accuracy                           0.51       148
   macro avg       0.68      0.68      0.64       148
weighted avg       0.57      0.51      0.48       148


 confusion_matrix:
 [[10  0  0]
 [ 0 21 60]
 [ 0 13 44]]
LogisticRegression Recall score 0.6770630279402209
LogisticRegression Precision score 0.6802413273001507


In [111]:
voting_clf = VotingClassifier(estimators=[('KNN', model1), ('LSVC', model3), ('LR', model5)],voting='hard')
voting_clf.fit(X_train, y_train)
for clf in (model1, model3, model5, voting_clf): 
    clf.fit(X_train, y_train)
    y2 = clf.predict(X1)
    print(clf.__class__.__name__, accuracy_score(y1, y2)) 
    print(classification_report(y1, y2))
    print('\n confusion_matrix:\n', confusion_matrix(y1, y2))

KNeighborsClassifier 0.5743243243243243
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.59      0.72      0.65        81
           2       0.42      0.30      0.35        57

    accuracy                           0.57       148
   macro avg       0.67      0.67      0.67       148
weighted avg       0.56      0.57      0.56       148


 confusion_matrix:
 [[10  0  0]
 [ 0 58 23]
 [ 0 40 17]]
LinearSVC 0.5472972972972973
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.58      0.62      0.60        81
           2       0.40      0.37      0.39        57

    accuracy                           0.55       148
   macro avg       0.66      0.66      0.66       148
weighted avg       0.54      0.55      0.54       148


 confusion_matrix:
 [[10  0  0]
 [ 0 50 31]
 [ 0 36 21]]
LogisticRegression 0.5067567567567568
              p